### GET ALL
GET http://localhost:3000/api/characters/classes

### POST
# @name createCharacterClass
POST http://localhost:3000/api/characters/classes
Content-Type: application/json

{
    "name": "Lord Sith",
    "description": "A wielder of the force who has embraced the dark side"
}

### ID
@id = {{createCharacterClass.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/characters/classes/{{id}}

### PUT
PUT http://localhost:3000/api/characters/classes/{{id}}
Content-Type: application/json

{
    "name": "Lord Sith",
    "description": "Wielder of the force who has embraced the dark side"
}